security:
    encoders:
        App\Entity\User:
            algorithm: auto


    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: lazy
            provider: app_user_provider
            logout:
                path: app_logout
            guard:
                authenticators:
                    - App\Security\Authenticator

    access_control:
        - { path: ^/login, allow_if: is_anonymous() }
        - { path: ^/users/create, allow_if: is_anonymous() }
        - { path: ^/users/\d+/edit, roles: ROLE_USER }
        - { path: ^/users/list, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
